export const IDS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
export const ROLES_DEF = [
  "Killer",
  "Victim",
  "Witness",
  "Accomplice",
  "Innocent",
];
export const MYSTERY_WORDS = [
  "Mystery",
  "Case",
  "Conundrum",
  "Enigma",
  "Puzzle",
  "Affair",
  "Investigation",
  "Riddle",
  "Situation",
  "Intrigue",
  "Riddle",
  "Conspiracy",
  "Crime",
  "Homicide",
  "Scenario",
  "Inquiry",
  "Scheme",
];
export const DIFFICULTY_ICONS = [
  "star",
  "skull",
  "sword",
  "lightbulb",
  "smiley-x-eyes",
  "knife",
  "bomb",
  "detective",
];

// Sizing word pools for case size descriptors
export const SIZING_WORDS = {
  3: ["Cozy", "Compact", "Snug", "Minimal", "Brief"],
  4: ["Intimate", "Personal", "Select", "Tight", "Close-knit"],
  5: ["Tense", "Gripping", "Fraught", "Charged", "Edgy"],
  6: ["Complex", "Intricate", "Elaborate", "Tangled", "Knotty"],
  7: ["Massive", "Grand", "Epic", "Sprawling", "Labyrinthine"],
};

// Kill-verb family keys — each string lives here exactly once.
const kSTAB = "STAB";
const kSHOOT = "SHOOT";
const kBLUDGEON = "BLUDGEON";
const kSTRANGLE = "STRANGLE";
const kPOISON = "POISON";
const kSLASH = "SLASH";
const kBURN = "BURN";
const kELECTROCUTE = "ELECTROCUTE";
const kINCAPACITATE = "INCAPACITATE";
const kELIMINATE = "ELIMINATE";

// Kill-verb synonym families. Items reference a key; render time picks one synonym.
export const KILL_VERB_GROUPS = {
  [kSTAB]: ["stab", "impale", "pierce", "run through"],
  [kSHOOT]: ["shoot", "fire at", "blast", "gun down"],
  [kBLUDGEON]: ["bludgeon", "beat", "bash", "strike", "club"],
  [kSTRANGLE]: ["strangle", "choke", "suffocate"],
  [kPOISON]: ["poison", "drug", "inject"],
  [kSLASH]: ["slash", "cut", "slice", "hack"],
  [kBURN]: ["burn", "incinerate", "scorch"],
  [kELECTROCUTE]: ["electrocute", "shock", "fry"],
  [kINCAPACITATE]: ["incapacitate", "disable", "neutralize"],
  [kELIMINATE]: ["eliminate", "dispatch", "kill"],
};

export const SCENARIOS = [
  {
    id: "stellar_voyage",
    name: "Stellar Voyage",
    alternateNames: ["Deep Space", "Starship", "Final Frontier", "Warp Speed"],
    suspects: [
      "Capt. Beaumont",
      "Cmdr. Hayes",
      "Lt. Cmdr. Logic",
      "Counselor Vane",
      "Lt. Drakov",
      "Dr. Mercer",
      "Lt. Cmdr. Weaver",
      "The Oracle",
      "Lt. Harlow",
      "Chief O'Malley",
      "The Entity",
      "Ensign Elkins",
      "Ensign Reed",
    ],
    rooms: [
      { name: "Command Bridge", noArticle: false, isProper: true },
      { name: "The Galley", noArticle: false, isProper: true },
      { name: "Main Engineering", noArticle: true, isProper: true },
      { name: "Simulation Deck", noArticle: false, isProper: true },
      { name: "Medical Bay", noArticle: true, isProper: true },
      { name: "Teleportation Suite", noArticle: false, isProper: true },
      { name: "Captain's Study", noArticle: false, isProper: true },
      { name: "Research Lab", noArticle: false, isProper: true },
      { name: "Hangar Bay", noArticle: false, isProper: true },
      { name: "Conference Lounge", noArticle: false, isProper: true },
      { name: "Storage Deck", noArticle: false, isProper: true },
    ],
    roomFeatures: {
      "Command Bridge": [
        { name: "Captain's chair", spillable: true },
        { name: "tactical station", spillable: true },
        { name: "viewscreen", spillable: true },
        { name: "turbolift", spillable: true },
        { name: "helm control", spillable: true },
      ],
      "The Galley": [
        { name: "bar", spillable: true },
        { name: "large windows", spillable: true },
        { name: "3D chess set", spillable: true },
        { name: "replicator", spillable: true },
        { name: "synthale dispenser", spillable: true },
      ],
      "Main Engineering": [
        { name: "warp core", spillable: true },
        { name: "isolinear racks", spillable: true },
        { name: "master systems display", spillable: true },
        { name: "henderson tube", spillable: true },
        { name: "dilithium chamber", spillable: true },
      ],
      "Simulation Deck": [
        { name: "arch", spillable: true },
        { name: "yellow grid", spillable: true },
        { name: "control panel", spillable: true },
        { name: "holographic emitter", spillable: true },
        { name: "safeties manual", spillable: true },
      ],
      "Medical Bay": [
        { name: "biobed", spillable: true },
        { name: "medical scanner", spillable: true },
        { name: "surgical arch", spillable: true },
        { name: "hypospray rack", spillable: true },
        { name: "desktop monitor", spillable: true },
      ],
      "Teleportation Suite": [
        { name: "transporter pad", spillable: true },
        { name: "control console", spillable: true },
        { name: "pattern buffer", spillable: true },
        { name: "targeting scanner", spillable: true },
        { name: "sliding doors", spillable: true },
      ],
      "Captain's Study": [
        { name: "fish tank", spillable: true },
        { name: "desk", spillable: true },
        { name: "sofa", spillable: true },
        { name: "shakespeare volume", spillable: true },
        { name: "earl grey replicator", spillable: true },
      ],
      "Research Lab": [
        { name: "microscopes", spillable: true },
        { name: "sensor array", spillable: true },
        { name: "stasis field", spillable: true },
        { name: "specimen container", spillable: true },
        { name: "laser cutter", spillable: true },
      ],
      "Hangar Bay": [
        { name: "shuttlecraft", spillable: true },
        { name: "launch pad", spillable: true },
        { name: "atmospheric forcefield", spillable: true },
        { name: "cargo crates", spillable: true },
        { name: "flight control", spillable: true },
      ],
      "Conference Lounge": [
        { name: "model ships", spillable: true },
        { name: "long table", spillable: true },
        { name: "viewports", spillable: false },
        { name: "gold ship relief", spillable: true },
        { name: "presentation screen", spillable: true },
      ],
      "Storage Deck": [
        { name: "shipping containers", spillable: true },
        { name: "anti-grav sled", spillable: true },
        { name: "blue barrel", spillable: true },
        { name: "forcefield control", spillable: true },
        { name: "airlock", spillable: true },
      ],
    },
    roomAdjacency: {
      // Spaceship corridor layout
      "Command Bridge": ["Conference Lounge", "Captain's Study"],
      "Captain's Study": ["Command Bridge"],
      "Conference Lounge": ["Command Bridge", "The Galley"],
      "The Galley": ["Conference Lounge", "Medical Bay"],
      "Medical Bay": ["The Galley", "Research Lab"],
      "Research Lab": ["Medical Bay", "Simulation Deck"],
      "Simulation Deck": ["Research Lab"],
      "Main Engineering": ["Storage Deck", "Hangar Bay", "Teleportation Suite"],
      "Storage Deck": ["Main Engineering"],
      "Hangar Bay": ["Main Engineering"],
      "Teleportation Suite": ["Main Engineering"],
    },
    items: [
      { name: "Pulse Pistol", isProper: false, bloody: true, killVerb: kSHOOT },
      {
        name: "Crescent Blade",
        isProper: false,
        bloody: true,
        killVerb: kSLASH,
      },
      {
        name: "Plasma Cutter",
        isProper: false,
        bloody: true,
        killVerb: kSLASH,
      },
      {
        name: "Pressure Injector",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      {
        name: "Particle Beam",
        isProper: false,
        bloody: false,
        killVerb: kSHOOT,
      },
      {
        name: "Stun Baton",
        isProper: false,
        bloody: false,
        killVerb: kBLUDGEON,
      },
      {
        name: "Carved Idol",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Ancient Flute",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Self-sealing stem bolts",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      { name: "Plasma Torch", isProper: false, bloody: false, killVerb: kBURN },
      {
        name: "English Teapot",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
    ],
  },
  {
    id: "classic_manor",
    name: "Estate of Mystery",
    alternateNames: ["Manor House", "Estate", "Country House"],
    suspects: [
      "Commander Hawthorne",
      "Lady Valentine",
      "Dean Whitmore",
      "Julian Forest",
      "Baroness Nightingale",
      "Madam Vane",
      "Inspector Slate",
      "Clementine",
      "Mrs. Gable",
      "Admiral Birch",
    ],
    rooms: [
      { name: "Kitchen", noArticle: false, isProper: false },
      { name: "Ballroom", noArticle: false, isProper: false },
      { name: "Conservatory", noArticle: false, isProper: false },
      { name: "Library", noArticle: false, isProper: false },
      { name: "Study", noArticle: false, isProper: false },
      { name: "Hall", noArticle: false, isProper: false },
      { name: "Lounge", noArticle: false, isProper: false },
      { name: "Dining Room", noArticle: false, isProper: false },
      { name: "Billiard Room", noArticle: false, isProper: false },
      { name: "Cellar", noArticle: false, isProper: false },
      { name: "Attic", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      Kitchen: [
        { name: "iron stove", spillable: true },
        { name: "walk-in pantry", spillable: true },
        { name: "butcher block", spillable: true },
        { name: "copper pans", spillable: true },
        { name: "dumbwaiter", spillable: true },
      ],
      Ballroom: [
        { name: "grand piano", spillable: true },
        { name: "crystal chandelier", spillable: true },
        { name: "musicians' gallery", spillable: true },
        { name: "polished floor", spillable: true },
        { name: "french doors", spillable: true },
      ],
      Conservatory: [
        { name: "exotic plants", spillable: true },
        { name: "glass roof", spillable: true },
        { name: "wicker furniture", spillable: true },
        { name: "stone fountain", spillable: true },
        { name: "potting bench", spillable: true },
      ],
      Library: [
        { name: "tall bookshelves", spillable: true },
        { name: "sliding ladder", spillable: true },
        { name: "reading chair", spillable: true },
        { name: "antique globe", spillable: true },
        { name: "bust of Pallas", spillable: true },
      ],
      Study: [
        { name: "stone fireplace", spillable: true },
        { name: "wall safe", spillable: true },
        { name: "mahogany desk", spillable: true },
        { name: "leather armchair", spillable: true },
        { name: "oil portrait", spillable: true },
      ],
      Hall: [
        { name: "grand staircase", spillable: true },
        { name: "coat rack", spillable: true },
        { name: "telephone", spillable: true },
        { name: "grandfather clock", spillable: true },
        { name: "umbrella stand", spillable: true },
      ],
      Lounge: [
        { name: "velvet sofa", spillable: true },
        { name: "gramophone", spillable: true },
        { name: "drinks trolley", spillable: true },
        { name: "heavy curtains", spillable: true },
        { name: "card table", spillable: true },
      ],
      "Dining Room": [
        { name: "silverware", spillable: true },
        { name: "banquet table", spillable: true },
        { name: "oak sideboard", spillable: true },
        { name: "candelabra", spillable: true },
        { name: "crystal glasses", spillable: true },
      ],
      "Billiard Room": [
        { name: "pool table", spillable: true },
        { name: "cue rack", spillable: true },
        { name: "dartboard", spillable: true },
        { name: "trophy cabinet", spillable: true },
        { name: "smoking stand", spillable: true },
      ],
      Cellar: [
        { name: "wine barrels", spillable: true },
        { name: "coal chute", spillable: true },
        { name: "fuse box", spillable: true },
        { name: "cobwebs", spillable: true },
        { name: "workbench", spillable: true },
      ],
      Attic: [
        { name: "old trunks", spillable: true },
        { name: "dusty mirrors", spillable: true },
        { name: "dress form", spillable: true },
        { name: "rocking horse", spillable: true },
        { name: "exposed beams", spillable: true },
      ],
    },
    roomAdjacency: {
      // Hall as central hub
      Hall: ["Ballroom", "Library", "Study", "Lounge", "Dining Room"],
      Ballroom: ["Hall", "Conservatory"],
      Conservatory: ["Ballroom"],
      Library: ["Hall", "Study"],
      Study: ["Hall", "Library"],
      Lounge: ["Hall", "Billiard Room"],
      "Dining Room": ["Hall", "Kitchen"],
      Kitchen: ["Dining Room", "Cellar"],
      "Billiard Room": ["Lounge"],
      Cellar: ["Kitchen"],
      // Attic isolated (accessed by stairs)
    },
    items: [
      {
        name: "Candlestick",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      { name: "Dagger", isProper: false, bloody: true, killVerb: kSTAB },
      { name: "Lead Pipe", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Revolver", isProper: false, bloody: true, killVerb: kSHOOT },
      { name: "Rope", isProper: false, bloody: false, killVerb: kSTRANGLE },
      { name: "Wrench", isProper: false, bloody: true, killVerb: kBLUDGEON },
      {
        name: "Poison Bottle",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      { name: "Horseshoe", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Trophy", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Poker", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Axe", isProper: false, bloody: true, killVerb: kSLASH },
    ],
  },
  {
    id: "medieval",
    name: "Medieval Castle",
    alternateNames: ["Castle Keep", "Fortress", "Stronghold", "Keep"],
    suspects: [
      "Sir Alistair",
      "Lady Eleanor",
      "The Friar",
      "The Minstrel",
      "The Blacksmith",
      "Princess Isabella",
      "The Jester",
      "The Alchemist",
      "The Squire",
      "The Abbess",
      "The Huntsman",
      "The Herbalist",
      "The Knight",
    ],
    rooms: [
      { name: "Throne Room", noArticle: false, isProper: false },
      { name: "Great Hall", noArticle: false, isProper: false },
      { name: "Dungeon", noArticle: false, isProper: false },
      { name: "Armory", noArticle: false, isProper: false },
      { name: "Chapel", noArticle: false, isProper: false },
      { name: "Stable", noArticle: false, isProper: false },
      { name: "Tower", noArticle: false, isProper: false },
      { name: "Courtyard", noArticle: false, isProper: false },
      { name: "Barracks", noArticle: false, isProper: false },
      { name: "Gatehouse", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      "Throne Room": [
        { name: "golden throne", spillable: true },
        { name: "heraldic banners", spillable: true },
        { name: "royal dais", spillable: true },
        { name: "stone crest", spillable: true },
        { name: "guard post", spillable: true },
      ],
      "Great Hall": [
        { name: "long table", spillable: true },
        { name: "roaring hearth", spillable: true },
        { name: "minstrel's gallery", spillable: true },
        { name: "faded tapestry", spillable: true },
        { name: "roasting spit", spillable: true },
      ],
      Dungeon: [
        { name: "rusty chains", spillable: true },
        { name: "damp straw", spillable: true },
        { name: "iron shackles", spillable: true },
        { name: "water drip", spillable: true },
        { name: "wooden stocks", spillable: true },
      ],
      Armory: [
        { name: "shield rack", spillable: true },
        { name: "sharp swords", spillable: true },
        { name: "whetstone", spillable: true },
        { name: "armor stand", spillable: true },
        { name: "training dummy", spillable: true },
      ],
      Chapel: [
        { name: "stone altar", spillable: true },
        { name: "stained glass", spillable: true },
        { name: "wooden pews", spillable: true },
        { name: "holy relic", spillable: true },
        { name: "confessional", spillable: true },
      ],
      Stable: [
        { name: "fresh hay", spillable: true },
        { name: "horse stalls", spillable: true },
        { name: "water trough", spillable: true },
        { name: "saddle rack", spillable: true },
        { name: "pitchfork", spillable: true },
      ],
      Tower: [
        { name: "spiral stairs", spillable: true },
        { name: "arrow slit", spillable: true },
        { name: "brass telescope", spillable: true },
        { name: "warning bell", spillable: true },
        { name: "trapdoor", spillable: true },
      ],
      Courtyard: [
        { name: "stone well", spillable: true },
        { name: "target dummies", spillable: true },
        { name: "wooden stocks", spillable: true },
        { name: "central fountain", spillable: true },
        { name: "cobblestones", spillable: true },
      ],
      Barracks: [
        { name: "wooden bunks", spillable: true },
        { name: "armor stands", spillable: true },
        { name: "dice table", spillable: true },
        { name: "weapon rack", spillable: true },
        { name: "footlocker", spillable: true },
      ],
      Gatehouse: [
        { name: "iron portcullis", spillable: true },
        { name: "heavy winch", spillable: true },
        { name: "murder holes", spillable: true },
        { name: "drawbridge control", spillable: true },
        { name: "boiling oil", spillable: true },
      ],
    },
    roomAdjacency: {
      // Courtyard as central hub
      Courtyard: ["Gatehouse", "Great Hall", "Chapel", "Stable", "Barracks"],
      Gatehouse: ["Courtyard"],
      "Great Hall": ["Courtyard", "Throne Room", "Armory"],
      "Throne Room": ["Great Hall", "Tower"],
      Armory: ["Great Hall"],
      Chapel: ["Courtyard"],
      Stable: ["Courtyard"],
      Barracks: ["Courtyard"],
      Tower: ["Throne Room"],
      Dungeon: ["Great Hall"],
    },
    items: [
      { name: "Broadsword", isProper: false, bloody: true, killVerb: kSLASH },
      { name: "Chalice", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Crossbow", isProper: false, bloody: true, killVerb: kSHOOT },
      {
        name: "Poison Ring",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      { name: "Mace", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Flail", isProper: false, bloody: true, killVerb: kBLUDGEON },
      {
        name: "Morning Star",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Vial of Hemlock",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      { name: "Gauntlet", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Dagger", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "War Hammer",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
    ],
  },
  {
    id: "sherlock",
    name: "Sherlock Holmes",
    alternateNames: ["Baker Street", "Victorian Crime", "Holmes"],
    suspects: [
      "Sherlock Holmes",
      "Dr. Watson",
      "Inspector Lestrade",
      "Irene Adler",
      "Professor Moriarty",
      "Mrs. Hudson",
      "Mycroft Holmes",
      "Colonel Moran",
      "Mary Morstan",
      "Inspector Gregson",
      "Charles Augustus Milverton",
    ],
    rooms: [
      { name: "221B Baker Street", noArticle: true, isProper: true },
      { name: "Scotland Yard", noArticle: true, isProper: true },
      { name: "Diogenes Club", noArticle: false, isProper: true },
      { name: "Reichenbach Falls", noArticle: true, isProper: true },
      { name: "Opium Den", noArticle: false, isProper: false },
      { name: "British Museum", noArticle: false, isProper: true },
      { name: "Hyde Park", noArticle: true, isProper: true },
      { name: "Hansom Cab", noArticle: false, isProper: false },
      { name: "Music Hall", noArticle: false, isProper: false },
      { name: "Telegraph Office", noArticle: false, isProper: false },
      { name: "Mortuary", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      "221B Baker Street": [
        { name: "violin", spillable: true },
        { name: "persian slipper", spillable: true },
        { name: "chemical apparatus", spillable: true },
        { name: "bullet holes", spillable: true },
        { name: "magnifying glass", spillable: true },
      ],
      "Scotland Yard": [
        { name: "evidence locker", spillable: true },
        { name: "wanted posters", spillable: true },
        { name: "gas lamp", spillable: true },
        { name: "filing cabinets", spillable: true },
        { name: "inspector's desk", spillable: true },
      ],
      "Diogenes Club": [
        { name: "leather armchairs", spillable: true },
        { name: "silence rule sign", spillable: true },
        { name: "fireplace", spillable: true },
        { name: "newspaper rack", spillable: true },
        { name: "bow window", spillable: true },
      ],
      "Reichenbach Falls": [
        { name: "rushing water", spillable: true },
        { name: "narrow ledge", spillable: true },
        { name: "alpine air", spillable: false },
        { name: "walking stick", spillable: true },
        { name: "rocky precipice", spillable: true },
      ],
      "Opium Den": [
        { name: "smoke haze", spillable: false },
        { name: "dim lanterns", spillable: true },
        { name: "stained cushions", spillable: true },
        { name: "oriental rugs", spillable: true },
        { name: "doorway curtain", spillable: true },
      ],
      "British Museum": [
        { name: "glass cases", spillable: true },
        { name: "egyptian artifacts", spillable: true },
        { name: "marble columns", spillable: true },
        { name: "gaslight chandelier", spillable: true },
        { name: "reading room", spillable: true },
      ],
      "Hyde Park": [
        { name: "foggy paths", spillable: true },
        { name: "iron benches", spillable: true },
        { name: "gas street lamp", spillable: true },
        { name: "ornamental lake", spillable: true },
        { name: "autumn leaves", spillable: true },
      ],
      "Hansom Cab": [
        { name: "leather seats", spillable: true },
        { name: "small window", spillable: true },
        { name: "driver's reins", spillable: true },
        { name: "fog outside", spillable: false },
        { name: "carriage lamp", spillable: true },
      ],
      "Music Hall": [
        { name: "red velvet curtains", spillable: true },
        { name: "gaslights", spillable: true },
        { name: "brass instruments", spillable: true },
        { name: "performer stage", spillable: true },
        { name: "balcony seats", spillable: true },
      ],
      "Telegraph Office": [
        { name: "morse key", spillable: true },
        { name: "wire spools", spillable: true },
        { name: "message forms", spillable: true },
        { name: "clerk window", spillable: true },
        { name: "delivery boy", spillable: true },
      ],
      Mortuary: [
        { name: "examination table", spillable: true },
        { name: "gas burner", spillable: true },
        { name: "medical instruments", spillable: true },
        { name: "body drawer", spillable: true },
        { name: "formaldehyde", spillable: true },
      ],
    },
    items: [
      { name: "Revolver", isProper: false, bloody: true, killVerb: kSHOOT },
      { name: "Syringe", isProper: false, bloody: false, killVerb: kPOISON },
      {
        name: "Poison Vial",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      {
        name: "Walking Stick",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      { name: "Cane Sword", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Riding Crop",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      { name: "Letter Opener", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Fireplace Poker",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Brass Knuckles",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Chloroform Cloth",
        isProper: false,
        bloody: false,
        killVerb: kSTRANGLE,
      },
      { name: "Dagger", isProper: false, bloody: true, killVerb: kSTAB },
    ],
    relationships: [
      {
        type: "siblings",
        suspects: [
          { name: "Sherlock Holmes", term: "younger brother" },
          { name: "Mycroft Holmes", term: "older brother" },
        ],
      },
      {
        type: "married",
        suspects: [
          { name: "Dr. Watson", term: "husband" },
          { name: "Mary Morstan", term: "wife" },
        ],
        optional: true,
        probability: 0.7,
      },
      {
        type: "landlord-tenant",
        suspects: [
          { name: "Mrs. Hudson", term: "landlady" },
          { name: "Sherlock Holmes", term: "tenant" },
        ],
        optional: true,
        probability: 0.5,
      },
    ],
  },
  {
    id: "gatsby",
    name: "Great Gatsby",
    alternateNames: ["Roaring Twenties", "Jazz Age"],
    suspects: [
      "Jay Gatsby",
      "Nick Carraway",
      "Daisy Buchanan",
      "Tom Buchanan",
      "Jordan Baker",
      "Myrtle Wilson",
      "George Wilson",
      "Meyer Wolfsheim",
      "Klipspringer",
      "Owl Eyes",
      "Catherine",
    ],
    rooms: [
      { name: "Gatsby's Mansion", noArticle: true, isProper: true },
      { name: "East Egg", noArticle: true, isProper: true },
      { name: "West Egg", noArticle: true, isProper: true },
      { name: "Valley of Ashes", noArticle: false, isProper: true },
      { name: "Wilson's Garage", noArticle: true, isProper: true },
      { name: "Plaza Hotel", noArticle: false, isProper: true },
      { name: "Swimming Pool", noArticle: false, isProper: false },
      { name: "Ballroom", noArticle: false, isProper: false },
      { name: "Library", noArticle: false, isProper: false },
      { name: "Garden", noArticle: false, isProper: false },
      { name: "Dock", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      "Gatsby's Mansion": [
        { name: "grand piano", spillable: true },
        { name: "champagne fountain", spillable: true },
        { name: "marble columns", spillable: true },
        { name: "crystal chandelier", spillable: true },
        { name: "spiral staircase", spillable: true },
      ],
      "East Egg": [
        { name: "manicured lawns", spillable: true },
        { name: "white mansion", spillable: true },
        { name: "dock", spillable: true },
        { name: "boat house", spillable: true },
        { name: "formal gardens", spillable: true },
      ],
      "West Egg": [
        { name: "nouveau riche estates", spillable: true },
        { name: "gatsby's castle", spillable: true },
        { name: "overgrown ivy", spillable: true },
        { name: "jazz band", spillable: true },
        { name: "car collection", spillable: true },
      ],
      "Valley of Ashes": [
        { name: "gray dust", spillable: true },
        { name: "billboard eyes", spillable: true },
        { name: "ash heaps", spillable: true },
        { name: "railroad tracks", spillable: true },
        { name: "desolate wasteland", spillable: true },
      ],
      "Wilson's Garage": [
        { name: "oil drums", spillable: true },
        { name: "repair tools", spillable: true },
        { name: "dirt floor", spillable: true },
        { name: "rusty pumps", spillable: true },
        { name: "grimy windows", spillable: true },
      ],
      "Plaza Hotel": [
        { name: "gilded mirrors", spillable: true },
        { name: "art deco lamps", spillable: true },
        { name: "suite furnishings", spillable: true },
        { name: "champagne service", spillable: true },
        { name: "sweeping views", spillable: false },
      ],
      "Swimming Pool": [
        { name: "blue tiles", spillable: true },
        { name: "diving board", spillable: true },
        { name: "pool float", spillable: true },
        { name: "marble edge", spillable: true },
        { name: "deck chairs", spillable: true },
      ],
      Ballroom: [
        { name: "jazz orchestra", spillable: true },
        { name: "dancing couples", spillable: true },
        { name: "champagne towers", spillable: true },
        { name: "sparkling dresses", spillable: true },
        { name: "confetti", spillable: true },
      ],
      Library: [
        { name: "uncut books", spillable: true },
        { name: "owl eyes", spillable: true },
        { name: "leather chairs", spillable: true },
        { name: "tall shelves", spillable: true },
        { name: "reading lamp", spillable: true },
      ],
      Garden: [
        { name: "rose bushes", spillable: true },
        { name: "green light", spillable: false },
        { name: "water fountain", spillable: true },
        { name: "marble statues", spillable: true },
        { name: "trimmed hedges", spillable: true },
      ],
      Dock: [
        { name: "green light", spillable: false },
        { name: "wooden planks", spillable: true },
        { name: "boat slip", spillable: true },
        { name: "water lapping", spillable: false },
        { name: "stars above", spillable: false },
      ],
    },
    roomAdjacency: {
      // Mansion interior and grounds
      "Gatsby's Mansion": ["Library", "Ballroom", "Garden"],
      Library: ["Gatsby's Mansion"],
      Ballroom: ["Gatsby's Mansion"],
      Garden: ["Gatsby's Mansion", "Swimming Pool", "Dock"],
      "Swimming Pool": ["Garden"],
      Dock: ["Garden"],
      // Distant locations not connected
    },
    items: [
      { name: "Revolver", isProper: false, bloody: true, killVerb: kSHOOT },
      {
        name: "Broken Champagne Bottle",
        isProper: false,
        bloody: true,
        killVerb: kSLASH,
      },
      {
        name: "Crystal Decanter",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Whiskey Decanter",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Automobile",
        isProper: false,
        bloody: true,
        killVerb: kELIMINATE,
      },
      {
        name: "Silk Scarf",
        isProper: false,
        bloody: false,
        killVerb: kSTRANGLE,
      },
      {
        name: "Straight Razor",
        isProper: false,
        bloody: true,
        killVerb: kSLASH,
      },
      { name: "Letter Opener", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Fireplace Poker",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Pearl Necklace",
        isProper: false,
        bloody: false,
        killVerb: kSTRANGLE,
      },
      { name: "Golf Club", isProper: false, bloody: true, killVerb: kBLUDGEON },
    ],
    relationships: [
      {
        type: "married",
        suspects: [
          { name: "Tom Buchanan", term: "husband" },
          { name: "Daisy Buchanan", term: "wife" },
        ],
      },
      {
        type: "married",
        suspects: [
          { name: "George Wilson", term: "husband" },
          { name: "Myrtle Wilson", term: "wife" },
        ],
      },
    ],
  },
  {
    id: "falcon",
    name: "Maltese Falcon",
    alternateNames: [], // No alternates - fixed by characters
    suspects: [
      "Sam Spade",
      "Brigid O'Shaughnessy",
      "Joel Cairo",
      "Kasper Gutman",
      "Wilmer Cook",
      "Effie Perine",
      "Miles Archer",
      "Floyd Thursby",
      "Lt. Dundy",
      "Tom Polhaus",
      "Iva Archer",
    ],
    rooms: [
      { name: "Spade & Archer Office", noArticle: false, isProper: true },
      { name: "Hotel Room", noArticle: false, isProper: false },
      { name: "Gutman's Suite", noArticle: true, isProper: true },
      { name: "Alleyway", noArticle: false, isProper: false },
      { name: "Police Station", noArticle: false, isProper: false },
      { name: "Docks", noArticle: false, isProper: false },
      { name: "Apartment", noArticle: false, isProper: false },
      { name: "Bar", noArticle: false, isProper: false },
      { name: "Street Corner", noArticle: false, isProper: false },
      { name: "Lobby", noArticle: false, isProper: false },
      { name: "Warehouse", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      "Spade & Archer Office": [
        { name: "frosted glass door", spillable: true },
        { name: "wooden desk", spillable: true },
        { name: "filing cabinet", spillable: true },
        { name: "telephone", spillable: true },
        { name: "venetian blinds", spillable: true },
      ],
      "Hotel Room": [
        { name: "single bed", spillable: true },
        { name: "worn carpet", spillable: true },
        { name: "sink", spillable: true },
        { name: "window overlooking street", spillable: true },
        { name: "locked suitcase", spillable: true },
      ],
      "Gutman's Suite": [
        { name: "thick cigar smoke", spillable: false },
        { name: "bourbon decanter", spillable: true },
        { name: "plush furniture", spillable: true },
        { name: "oriental rug", spillable: true },
        { name: "heavy drapes", spillable: true },
      ],
      Alleyway: [
        { name: "fire escape", spillable: true },
        { name: "trash cans", spillable: true },
        { name: "wet cobblestones", spillable: true },
        { name: "dim light", spillable: false },
        { name: "brick walls", spillable: true },
      ],
      "Police Station": [
        { name: "interrogation table", spillable: true },
        { name: "holding cells", spillable: true },
        { name: "wanted posters", spillable: true },
        { name: "metal chairs", spillable: true },
        { name: "one-way mirror", spillable: true },
      ],
      Docks: [
        { name: "fog horn", spillable: true },
        { name: "cargo crates", spillable: true },
        { name: "ship gangway", spillable: true },
        { name: "rope coils", spillable: true },
        { name: "water slapping", spillable: false },
      ],
      Apartment: [
        { name: "murphy bed", spillable: true },
        { name: "kitchenette", spillable: true },
        { name: "radio", spillable: true },
        { name: "hat rack", spillable: true },
        { name: "rotary phone", spillable: true },
      ],
      Bar: [
        { name: "neon sign", spillable: true },
        { name: "bar stools", spillable: true },
        { name: "dartboard", spillable: true },
        { name: "jukebox", spillable: true },
        { name: "cigarette haze", spillable: false },
      ],
      "Street Corner": [
        { name: "street lamp", spillable: true },
        { name: "newsstand", spillable: true },
        { name: "fire hydrant", spillable: true },
        { name: "wet pavement", spillable: true },
        { name: "taxi stand", spillable: true },
      ],
      Lobby: [
        { name: "elevator gate", spillable: true },
        { name: "mailboxes", spillable: true },
        { name: "marble floor", spillable: true },
        { name: "potted palm", spillable: true },
        { name: "brass buttons", spillable: true },
      ],
      Warehouse: [
        { name: "stacked crates", spillable: true },
        { name: "elevator", spillable: true },
        { name: "high windows", spillable: true },
        { name: "loading bay", spillable: true },
        { name: "chain hoist", spillable: true },
      ],
    },
    items: [
      {
        name: "Maltese Falcon Statue",
        isProper: true,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      { name: "Revolver", isProper: false, bloody: true, killVerb: kSHOOT },
      { name: "Knife", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Whiskey Bottle",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      { name: "Lead Pipe", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Switchblade", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Brass Knuckles",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      { name: "Ice Pick", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Garrote Wire",
        isProper: false,
        bloody: false,
        killVerb: kSTRANGLE,
      },
      { name: "Sap", isProper: false, bloody: true, killVerb: kBLUDGEON },
      {
        name: "Poisoned Ring",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
    ],
  },
  {
    id: "continental_express",
    name: "Continental Express",
    alternateNames: ["Express", "Luxury Train", "Night Train", "Railway"],
    suspects: [
      "Auguste Lupa",
      "M. Renaud",
      "Baroness Von Zied",
      "Archduke Viktor",
      "Archduchess Elara",
      "Major Crawford",
      "Alice Pemberley",
      "Edmund Blackwell",
      "Ingrid Lindstrom",
      "Jean-Pierre",
      "Gretel Schwartz",
    ],
    rooms: [
      { name: "Dining Car", noArticle: false, isProper: true },
      { name: "Sleeping Compartment", noArticle: false, isProper: false },
      { name: "Observation Car", noArticle: false, isProper: true },
      { name: "First Class Corridor", noArticle: false, isProper: true },
      { name: "Second Class Coach", noArticle: false, isProper: true },
      { name: "Baggage Car", noArticle: false, isProper: true },
      { name: "Conductor's Cabin", noArticle: false, isProper: true },
      { name: "Kitchen Car", noArticle: false, isProper: true },
      { name: "Smoking Lounge", noArticle: false, isProper: false },
      { name: "Washroom", noArticle: false, isProper: false },
      { name: "Platform", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      "Dining Car": [
        { name: "white tablecloths", spillable: true },
        { name: "silver service", spillable: true },
        { name: "champagne bucket", spillable: true },
        { name: "crystal glasses", spillable: true },
        { name: "art deco lamps", spillable: true },
      ],
      "Sleeping Compartment": [
        { name: "fold-down bed", spillable: true },
        { name: "velvet curtains", spillable: true },
        { name: "reading lamp", spillable: true },
        { name: "washbasin", spillable: true },
        { name: "luggage rack", spillable: true },
      ],
      "Observation Car": [
        { name: "panoramic windows", spillable: true },
        { name: "leather seats", spillable: true },
        { name: "brass fixtures", spillable: true },
        { name: "mahogany paneling", spillable: true },
        { name: "snowy landscape", spillable: false },
      ],
      "First Class Corridor": [
        { name: "red carpet", spillable: true },
        { name: "polished wood", spillable: true },
        { name: "call buttons", spillable: true },
        { name: "brass handrails", spillable: true },
        { name: "framed art", spillable: true },
      ],
      "Second Class Coach": [
        { name: "bench seats", spillable: true },
        { name: "overhead luggage", spillable: true },
        { name: "coal heating", spillable: true },
        { name: "narrow aisle", spillable: true },
        { name: "curtained windows", spillable: true },
      ],
      "Baggage Car": [
        { name: "stacked trunks", spillable: true },
        { name: "locked crates", spillable: true },
        { name: "cargo netting", spillable: true },
        { name: "dim lighting", spillable: false },
        { name: "sliding door", spillable: true },
      ],
      "Conductor's Cabin": [
        { name: "timetable", spillable: true },
        { name: "telegraph", spillable: true },
        { name: "uniform jacket", spillable: true },
        { name: "lantern", spillable: true },
        { name: "logbook", spillable: true },
      ],
      "Kitchen Car": [
        { name: "brass pots", spillable: true },
        { name: "gas stove", spillable: true },
        { name: "spice rack", spillable: true },
        { name: "cutting boards", spillable: true },
        { name: "chef's knife", spillable: true },
      ],
      "Smoking Lounge": [
        { name: "leather club chairs", spillable: true },
        { name: "cigar humidor", spillable: true },
        { name: "brandy decanter", spillable: true },
        { name: "card table", spillable: true },
        { name: "venetian blinds", spillable: true },
      ],
      Washroom: [
        { name: "porcelain sink", spillable: true },
        { name: "brass fixtures", spillable: true },
        { name: "towel rack", spillable: true },
        { name: "mirror", spillable: true },
        { name: "soap dish", spillable: true },
      ],
      Platform: [
        { name: "snow drifts", spillable: true },
        { name: "frozen rails", spillable: true },
        { name: "luggage cart", spillable: true },
        { name: "station lamp", spillable: true },
        { name: "footprints", spillable: true },
      ],
    },
    roomAdjacency: {
      // Front to back train layout
      Platform: ["Conductor's Cabin"],
      "Conductor's Cabin": ["Platform", "First Class Corridor"],
      "First Class Corridor": [
        "Conductor's Cabin",
        "Sleeping Compartment",
        "Dining Car",
      ],
      "Sleeping Compartment": ["First Class Corridor"],
      "Dining Car": ["First Class Corridor", "Kitchen Car", "Observation Car"],
      "Kitchen Car": ["Dining Car", "Baggage Car"],
      "Observation Car": ["Dining Car", "Smoking Lounge"],
      "Baggage Car": ["Kitchen Car", "Second Class Coach"],
      "Second Class Coach": ["Baggage Car", "Washroom"],
      "Smoking Lounge": ["Observation Car", "Washroom"],
      Washroom: ["Second Class Coach", "Smoking Lounge"],
    },
    items: [
      { name: "Dagger", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Vial of Laudanum",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      {
        name: "Garrote Wire",
        isProper: false,
        bloody: false,
        killVerb: kSTRANGLE,
      },
      { name: "Letter Opener", isProper: false, bloody: true, killVerb: kSTAB },
      { name: "Hatpin", isProper: false, bloody: true, killVerb: kSTAB },
      { name: "Scissors", isProper: false, bloody: true, killVerb: kSTAB },
      { name: "Ice Pick", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Walking Cane",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Poison Ring",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      {
        name: "Heavy Pocket Watch",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Champagne Bottle",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
    ],
    relationships: [
      {
        type: "married",
        suspects: [
          { name: "Archduke Viktor", term: "husband" },
          { name: "Archduchess Elara", term: "wife" },
        ],
      },
      {
        type: "servant-employer",
        suspects: [
          { name: "Jean-Pierre", term: "servant" },
          { name: "Baroness Von Zied", term: "employer" },
        ],
        optional: true,
        probability: 0.6,
      },
      {
        type: "rivals",
        suspects: [
          { name: "M. Renaud", term: "rival" },
          { name: "Auguste Lupa", term: "rival" },
        ],
        optional: true,
        probability: 0.4,
      },
    ],
  },
  {
    id: "edge_walker",
    name: "Edge Walker",
    alternateNames: [
      "Neon City",
      "Electric Sheep",
      "Future Noir",
      "Street Level",
    ],
    suspects: [
      "Jack Marlowe",
      "Reina",
      "Rex Vane",
      "Pixel",
      "Viper",
      "Lukas Novak",
      "Arthur Finch",
      "Crane",
      "Silas Thorne",
      "Captain Miller",
      "Doctor Frost",
    ],
    rooms: [
      { name: "Thorne Corporation", noArticle: false, isProper: true },
      { name: "Marlowe's Apartment", noArticle: true, isProper: true },
      { name: "The Grand Atrium", noArticle: false, isProper: true },
      { name: "The Gilded Lounge", noArticle: true, isProper: true },
      { name: "Finch's Workshop", noArticle: true, isProper: true },
      { name: "Police Headquarters", noArticle: true, isProper: true },
      { name: "Neon District Street", noArticle: false, isProper: true },
      { name: "The Optical Lab", noArticle: true, isProper: true },
      { name: "Synthetic Row", noArticle: true, isProper: true },
      { name: "Rooftop", noArticle: false, isProper: false },
      { name: "Patrol Flyer", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      "Thorne Corporation": [
        { name: "pyramid architecture", spillable: true },
        { name: "owl", spillable: true },
        { name: "floor-to-ceiling windows", spillable: true },
        { name: "chess set", spillable: true },
        { name: "soft amber light", spillable: false },
      ],
      "Marlowe's Apartment": [
        { name: "piano", spillable: true },
        { name: "photographs", spillable: true },
        { name: "whiskey bottle", spillable: true },
        { name: "dim lighting", spillable: false },
        { name: "balcony door", spillable: true },
      ],
      "The Grand Atrium": [
        { name: "ornate ironwork", spillable: true },
        { name: "skylights", spillable: true },
        { name: "elevators", spillable: true },
        { name: "pigeons", spillable: true },
        { name: "art nouveau details", spillable: true },
      ],
      "The Gilded Lounge": [
        { name: "neon signs", spillable: true },
        { name: "snake dancer", spillable: true },
        { name: "crowded tables", spillable: true },
        { name: "smoke haze", spillable: false },
        { name: "mirrored walls", spillable: true },
      ],
      "Finch's Workshop": [
        { name: "mechanical toys", spillable: true },
        { name: "mannequins", spillable: true },
        { name: "workbench", spillable: true },
        { name: "chess automaton", spillable: true },
        { name: "makeshift laboratory", spillable: true },
      ],
      "Police Headquarters": [
        { name: "voigt-kampff machine", spillable: true },
        { name: "filing system", spillable: true },
        { name: "fluorescent lights", spillable: false },
        { name: "wanted photos", spillable: true },
        { name: "spinner bay", spillable: true },
      ],
      "Neon District Street": [
        { name: "neon kanji", spillable: true },
        { name: "steam vents", spillable: true },
        { name: "rain", spillable: false },
        { name: "food vendors", spillable: true },
        { name: "hovering billboards", spillable: true },
      ],
      "The Optical Lab": [
        { name: "freezers", spillable: true },
        { name: "examination tools", spillable: true },
        { name: "microscope", spillable: true },
        { name: "cold air", spillable: false },
        { name: "artificial eyes", spillable: true },
      ],
      "Synthetic Row": [
        { name: "cages", spillable: true },
        { name: "synthetic animals", spillable: true },
        { name: "neon lights", spillable: false },
        { name: "crowded stalls", spillable: true },
        { name: "artificial snake", spillable: true },
      ],
      Rooftop: [
        { name: "rain", spillable: false },
        { name: "neon glow", spillable: false },
        { name: "ledge", spillable: true },
        { name: "pigeons", spillable: true },
        { name: "city lights", spillable: false },
      ],
      "Patrol Flyer": [
        { name: "controls", spillable: true },
        { name: "rain on windshield", spillable: false },
        { name: "police radio", spillable: true },
        { name: "confined space", spillable: false },
        { name: "glowing displays", spillable: false },
      ],
    },
    roomAdjacency: {
      // Roy's death scene connection
      Rooftop: ["Finch's Workshop"],
      "Finch's Workshop": ["Rooftop"],
    },
    items: [
      { name: "Blaster", isProper: false, bloody: true, killVerb: kSHOOT },
      { name: "Glass Shard", isProper: false, bloody: true, killVerb: kSLASH },
      { name: "Razor", isProper: false, bloody: true, killVerb: kSLASH },
      {
        name: "Venom Injector",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      {
        name: "Electric Probe",
        isProper: false,
        bloody: false,
        killVerb: kELECTROCUTE,
      },
      {
        name: "Garrote Wire",
        isProper: false,
        bloody: false,
        killVerb: kSTRANGLE,
      },
      {
        name: "Shock Baton",
        isProper: false,
        bloody: false,
        killVerb: kELECTROCUTE,
      },
      { name: "Knife", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Metal Pipe",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Sharpened Metal Rod",
        isProper: false,
        bloody: true,
        killVerb: kSTAB,
      },
      {
        name: "Neural Disruptor",
        isProper: false,
        bloody: false,
        killVerb: kINCAPACITATE,
      },
    ],
  },
  {
    id: "radio_shrink",
    name: "Pompous Psychiatrist",
    alternateNames: ["Radio Hour", "Psychiatrist"],
    suspects: [
      "Dr. Alistair Heron",
      "Dr. Malcolm Heron",
      "Clara Skye",
      "Arthur Heron",
      "Ruby Reed",
      "Terrier Thompson",
      "Vesta Vane",
      "Guy Kensington",
      "Hester Coldwell",
      "Danny Darrow",
      "Kevin Cross",
    ],
    rooms: [
      { name: "Alistair's Penthouse", noArticle: true, isProper: true },
      { name: "K-TALK Studio", noArticle: false, isProper: true },
      { name: "Cafe Caffeine", noArticle: true, isProper: true },
      { name: "Malcolm's Residence", noArticle: true, isProper: true },
      { name: "The Majestic", noArticle: false, isProper: true },
      { name: "Vintage Society", noArticle: false, isProper: false },
      { name: "The Grand Opera", noArticle: false, isProper: false },
      { name: "Sullivan's Pub", noArticle: true, isProper: true },
      { name: "The Spire", noArticle: false, isProper: true },
      { name: "Underground Garage", noArticle: false, isProper: false },
      { name: "Gallery Modern", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      "Alistair's Penthouse": [
        { name: "designer chair", spillable: true },
        { name: "city skyline view", spillable: false },
        { name: "baby grand", spillable: true },
        { name: "tribal artifacts", spillable: true },
        { name: "tattered recliner", spillable: true },
      ],
      "K-TALK Studio": [
        { name: "condenser mic", spillable: true },
        { name: "fader board", spillable: true },
        { name: "live signal", spillable: true },
        { name: "isolation booth", spillable: true },
        { name: "switchboard", spillable: true },
      ],
      "Cafe Caffeine": [
        { name: "steam wand", spillable: true },
        { name: "croissant tray", spillable: true },
        { name: "marble tables", spillable: true },
        { name: "periodical stand", spillable: true },
        { name: "beverage counter", spillable: true },
      ],
      "Malcolm's Residence": [
        { name: "silk rugs", spillable: true },
        { name: "baroque decor", spillable: true },
        { name: "concert piano", spillable: true },
        { name: "bone china", spillable: true },
        { name: "first editions", spillable: true },
      ],
      "The Majestic": [
        { name: "concierge lift", spillable: true },
        { name: "reception desk", spillable: true },
        { name: "checkerboard floors", spillable: true },
        { name: "ornate mirrors", spillable: true },
        { name: "porter station", spillable: true },
      ],
      "Vintage Society": [
        { name: "cellar casks", spillable: true },
        { name: "crystal stems", spillable: true },
        { name: "cellar master", spillable: true },
        { name: "storage racks", spillable: true },
        { name: "charcuterie", spillable: true },
      ],
      "The Grand Opera": [
        { name: "crimson seating", spillable: true },
        { name: "gilded molding", spillable: true },
        { name: "light fixture", spillable: false },
        { name: "pit floor", spillable: true },
        { name: "private boxes", spillable: true },
      ],
      "Sullivan's Pub": [
        { name: "tap handles", spillable: true },
        { name: "brass targets", spillable: true },
        { name: "billiards table", spillable: true },
        { name: "brewery signs", spillable: true },
        { name: "pennants", spillable: true },
      ],
      "The Spire": [
        { name: "lookout platform", spillable: true },
        { name: "skylounge", spillable: true },
        { name: "souvenirs", spillable: true },
        { name: "monoculars", spillable: true },
        { name: "floor-to-ceiling glass", spillable: true },
      ],
      "Underground Garage": [
        { name: "cement columns", spillable: true },
        { name: "pay stations", spillable: true },
        { name: "luxury sedan", spillable: true },
        { name: "grease marks", spillable: true },
        { name: "stairwell", spillable: true },
      ],
      "Gallery Modern": [
        { name: "abstract forms", spillable: true },
        { name: "blank walls", spillable: true },
        { name: "spotlighting", spillable: false },
        { name: "sparkling water", spillable: true },
        { name: "curator's podium", spillable: true },
      ],
    },
    items: [
      {
        name: "Wine Bottle",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Broadcasting Award",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Brass Poker",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Silver Slitter",
        isProper: false,
        bloody: true,
        killVerb: kSLASH,
      },
      { name: "Tailor Shears", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Lug Wrench",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Sommelier Tool",
        isProper: false,
        bloody: true,
        killVerb: kSTAB,
      },
      { name: "Nine Iron", isProper: false, bloody: true, killVerb: kBLUDGEON },
      {
        name: "Shard of Crystal",
        isProper: false,
        bloody: true,
        killVerb: kSLASH,
      },
      {
        name: "Encyclopedic Tome",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Ceremonial Dagger",
        isProper: false,
        bloody: true,
        killVerb: kSTAB,
      },
    ],
    relationships: [
      {
        type: "siblings",
        suspects: [
          { name: "Dr. Alistair Heron", term: "older brother" },
          { name: "Dr. Malcolm Heron", term: "younger brother" },
        ],
      },
      {
        type: "parent-child",
        suspects: [
          { name: "Arthur Heron", term: "father" },
          { name: "Dr. Alistair Heron", term: "son" },
        ],
      },
      {
        type: "parent-child",
        suspects: [
          { name: "Arthur Heron", term: "father" },
          { name: "Dr. Malcolm Heron", term: "son" },
        ],
      },
      {
        type: "colleagues",
        suspects: [
          { name: "Dr. Alistair Heron", term: "colleague" },
          { name: "Clara Skye", term: "colleague" },
        ],
        optional: true,
        probability: 0.6,
      },
    ],
  },
  {
    id: "indigo_heir",
    name: "Indigo Heir",
    alternateNames: [
      "Shifting Rooms",
      "Royal Estate",
      "Mansion",
      "Hidden Rooms",
      "Grand Estate",
    ],
    suspects: [
      "Simon B. Evans",
      "Cecily M. Evans",
      "David Evans",
      "Baron Horace M. Ashford",
      "Julian H. Ashford",
      "Martha Larsen",
      "Inspector Val Monet",
      "The Landscaper",
      "The Valet",
      "The Governess",
    ],
    rooms: [
      { name: "Drafting Studio", noArticle: false, isProper: true },
      { name: "Library", noArticle: false, isProper: false },
      { name: "Observatory", noArticle: false, isProper: false },
      { name: "Master Bedroom", noArticle: false, isProper: false },
      { name: "Secret Passage", noArticle: false, isProper: false },
      { name: "Chapel", noArticle: false, isProper: false },
      { name: "Greenhouse", noArticle: false, isProper: false },
      { name: "Dining Room", noArticle: false, isProper: false },
      { name: "Great Hall", noArticle: false, isProper: false },
      { name: "Terrace", noArticle: false, isProper: false },
      { name: "Room 99", noArticle: true, isProper: true },
    ],
    roomFeatures: {
      "Drafting Studio": [
        { name: "architectural plans", spillable: true },
        { name: "drafting table", spillable: true },
        { name: "compass", spillable: true },
        { name: "blueprints", spillable: true },
        { name: "sketching tools", spillable: true },
      ],
      Library: [
        { name: "tall bookshelves", spillable: true },
        { name: "reading chair", spillable: true },
        { name: "card catalog", spillable: true },
        { name: "fireplace", spillable: true },
        { name: "ladder", spillable: true },
      ],
      Observatory: [
        { name: "telescope", spillable: true },
        { name: "star charts", spillable: true },
        { name: "dome ceiling", spillable: true },
        { name: "viewing platform", spillable: false },
        { name: "celestial maps", spillable: true },
      ],
      "Master Bedroom": [
        { name: "four-poster bed", spillable: true },
        { name: "wardrobe", spillable: true },
        { name: "vanity", spillable: true },
        { name: "portrait", spillable: true },
        { name: "ornate rug", spillable: true },
      ],
      "Secret Passage": [
        { name: "hidden door", spillable: true },
        { name: "dusty corridor", spillable: true },
        { name: "cobwebs", spillable: true },
        { name: "torch sconce", spillable: true },
        { name: "stone walls", spillable: true },
      ],
      Chapel: [
        { name: "stained glass", spillable: true },
        { name: "wooden pews", spillable: true },
        { name: "altar", spillable: true },
        { name: "prayer books", spillable: true },
        { name: "candles", spillable: true },
      ],
      Greenhouse: [
        { name: "potted plants", spillable: true },
        { name: "glass panels", spillable: true },
        { name: "watering can", spillable: true },
        { name: "exotic flowers", spillable: true },
        { name: "humid air", spillable: false },
      ],
      "Dining Room": [
        { name: "long table", spillable: true },
        { name: "chandelier", spillable: true },
        { name: "place settings", spillable: true },
        { name: "sideboard", spillable: true },
        { name: "serving cart", spillable: true },
      ],
      "Great Hall": [
        { name: "grand staircase", spillable: true },
        { name: "suits of armor", spillable: true },
        { name: "tapestries", spillable: true },
        { name: "coat of arms", spillable: true },
        { name: "marble floor", spillable: true },
      ],
      Terrace: [
        { name: "stone balustrade", spillable: true },
        { name: "garden view", spillable: false },
        { name: "wrought iron", spillable: true },
        { name: "potted topiaries", spillable: true },
        { name: "morning light", spillable: false },
      ],
      "Room 99": [
        { name: "mystery door", spillable: true },
        { name: "ethereal glow", spillable: false },
        { name: "impossible geometry", spillable: false },
        { name: "shifting walls", spillable: true },
        { name: "hidden truth", spillable: false },
      ],
    },
    roomAdjacency: {
      // Manor with secret passages
      "Great Hall": ["Dining Room", "Library", "Chapel"],
      "Dining Room": ["Great Hall"],
      Library: ["Great Hall"],
      Chapel: ["Great Hall"],
      "Master Bedroom": ["Drafting Studio"],
      "Drafting Studio": ["Master Bedroom"],
      Greenhouse: ["Terrace"],
      Terrace: ["Greenhouse"],
      "Secret Passage": ["Observatory", "Room 99"],
      Observatory: ["Secret Passage"],
      "Room 99": ["Secret Passage"],
    },
    items: [
      {
        name: "Metal Detector",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Broken Lever",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      {
        name: "Magnifying Glass",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      { name: "Wrench", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Shovel", isProper: false, bloody: true, killVerb: kBLUDGEON },
      {
        name: "Watering Can",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      { name: "Hammer", isProper: false, bloody: true, killVerb: kBLUDGEON },
      {
        name: "Silver Spoon",
        isProper: false,
        bloody: true,
        killVerb: kBLUDGEON,
      },
      { name: "Crown", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Lunch Box", isProper: false, bloody: true, killVerb: kBLUDGEON },
      { name: "Telescope", isProper: false, bloody: true, killVerb: kBLUDGEON },
    ],
    relationships: [
      {
        type: "siblings",
        suspects: [
          { name: "Baron Horace M. Ashford", term: "older brother" },
          { name: "Julian H. Ashford", term: "younger brother" },
        ],
      },
      {
        type: "married",
        suspects: [
          { name: "Julian H. Ashford", term: "husband" },
          { name: "Martha Larsen", term: "wife" },
        ],
      },
      {
        type: "parent-child",
        suspects: [
          { name: "Julian H. Ashford", term: "father" },
          { name: "Cecily M. Evans", term: "daughter" },
        ],
      },
      {
        type: "parent-child",
        suspects: [
          { name: "Martha Larsen", term: "mother" },
          { name: "Cecily M. Evans", term: "daughter" },
        ],
      },
      {
        type: "married",
        suspects: [
          { name: "David Evans", term: "husband" },
          { name: "Cecily M. Evans", term: "wife" },
        ],
      },
      {
        type: "parent-child",
        suspects: [
          { name: "Cecily M. Evans", term: "mother" },
          { name: "Simon B. Evans", term: "son" },
        ],
      },
      {
        type: "parent-child",
        suspects: [
          { name: "David Evans", term: "father" },
          { name: "Simon B. Evans", term: "son" },
        ],
      },
      {
        type: "uncle-nephew",
        suspects: [
          { name: "Baron Horace M. Ashford", term: "great-uncle" },
          { name: "Simon B. Evans", term: "great-nephew" },
        ],
      },
    ],
  },
  {
    id: "shadow_protocol",
    name: "Shadow Protocol",
    alternateNames: ["Covert Ops", "Black Ops", "Classified"],
    suspects: [
      "Agent Cipher",
      "Agent Sparrow",
      "Dr. Konstantin Volkov",
      "Ambassador Rhodes",
      "Operative Nightingale",
      "Handler Grey",
      "Courier Phoenix",
      "Analyst Webb",
      "The Defector",
      "Station Chief Mercer",
      "Colonel Winters",
    ],
    rooms: [
      { name: "Embassy Annex", noArticle: false, isProper: true },
      { name: "Safe House", noArticle: false, isProper: false },
      { name: "Dead Drop Site", noArticle: false, isProper: false },
      { name: "Interrogation Room", noArticle: false, isProper: false },
      { name: "Handler's Office", noArticle: false, isProper: true },
      { name: "Surveillance Van", noArticle: false, isProper: false },
      { name: "Hotel Metropol", noArticle: false, isProper: true },
      { name: "Train Station", noArticle: false, isProper: false },
      { name: "Central Park", noArticle: true, isProper: true },
      { name: "Telephone Booth", noArticle: false, isProper: false },
      { name: "Underground Tunnel", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      "Embassy Annex": [
        { name: "classified files", spillable: true },
        { name: "cipher machine", spillable: true },
        { name: "secured telephone", spillable: true },
        { name: "flagpole", spillable: true },
        { name: "diplomatic seal", spillable: true },
      ],
      "Safe House": [
        { name: "false documents", spillable: true },
        { name: "disguise kit", spillable: true },
        { name: "radio transmitter", spillable: true },
        { name: "escape route", spillable: true },
        { name: "hidden compartment", spillable: true },
      ],
      "Dead Drop Site": [
        { name: "hollow tree", spillable: true },
        { name: "park bench", spillable: true },
        { name: "chalk mark", spillable: true },
        { name: "newspaper", spillable: true },
        { name: "trash bin", spillable: true },
      ],
      "Interrogation Room": [
        { name: "two-way mirror", spillable: true },
        { name: "recording device", spillable: true },
        { name: "metal chair", spillable: true },
        { name: "bright lamp", spillable: true },
        { name: "locked door", spillable: true },
      ],
      "Handler's Office": [
        { name: "burn bag", spillable: true },
        { name: "secure phone", spillable: true },
        { name: "world map", spillable: true },
        { name: "dossiers", spillable: true },
        { name: "whiskey decanter", spillable: true },
      ],
      "Surveillance Van": [
        { name: "listening equipment", spillable: true },
        { name: "camera feeds", spillable: true },
        { name: "headphones", spillable: true },
        { name: "tape recorder", spillable: true },
        { name: "periscope", spillable: true },
      ],
      "Hotel Metropol": [
        { name: "ornate lobby", spillable: true },
        { name: "elevator", spillable: true },
        { name: "room service cart", spillable: true },
        { name: "concierge desk", spillable: true },
        { name: "revolving door", spillable: true },
      ],
      "Train Station": [
        { name: "departure board", spillable: true },
        { name: "newspaper kiosk", spillable: true },
        { name: "luggage locker", spillable: true },
        { name: "platform", spillable: true },
        { name: "ticket window", spillable: true },
      ],
      "Central Park": [
        { name: "walking path", spillable: true },
        { name: "monument", spillable: true },
        { name: "pond", spillable: true },
        { name: "bridge", spillable: true },
        { name: "street lamp", spillable: true },
      ],
      "Telephone Booth": [
        { name: "rotary phone", spillable: true },
        { name: "phone book", spillable: true },
        { name: "graffiti", spillable: true },
        { name: "coin slot", spillable: true },
        { name: "accordion door", spillable: true },
      ],
      "Underground Tunnel": [
        { name: "steam pipes", spillable: true },
        { name: "maintenance access", spillable: true },
        { name: "dim bulbs", spillable: true },
        { name: "brick walls", spillable: true },
        { name: "iron ladder", spillable: true },
      ],
    },
    items: [
      {
        name: "Poisoned Umbrella",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      {
        name: "Silenced Pistol",
        isProper: false,
        bloody: true,
        killVerb: kSHOOT,
      },
      {
        name: "Poison Dart",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      {
        name: "Garrote Wire",
        isProper: false,
        bloody: false,
        killVerb: kSTRANGLE,
      },
      {
        name: "Lethal Syringe",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      {
        name: "Radioactive Pellet",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
      { name: "Poison Pen", isProper: false, bloody: false, killVerb: kPOISON },
      {
        name: "Car Brake Cable",
        isProper: false,
        bloody: false,
        killVerb: kELIMINATE,
      },
      { name: "Combat Knife", isProper: false, bloody: true, killVerb: kSTAB },
      { name: "Hidden Blade", isProper: false, bloody: true, killVerb: kSTAB },
      {
        name: "Toxin Applicator",
        isProper: false,
        bloody: false,
        killVerb: kPOISON,
      },
    ],
  },
];

export const CONFIG = {
  // All scenarios have equal weight
};
