export const IDS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
export const ROLES_DEF = [
  "Killer",
  "Victim",
  "Witness",
  "Accomplice",
  "Innocent",
];
export const SCENARIOS = [
  {
    id: "tng",
    name: "Star Trek: TNG",
    suspects: [
      "Capt. Picard",
      "Cmdr. Riker",
      "Lt. Cmdr. Data",
      "Counselor Troi",
      "Lt. Worf",
      "Dr. Crusher",
      "Lt. Cmdr. La Forge",
      "Guinan",
      "Lt. Barclay",
      "Chief O'Brien",
      "Q",
      "Ro Laren",
      "Tasha Yar",
    ],
    rooms: [
      { name: "Bridge", noArticle: false, isProper: true },
      { name: "Ten Forward", noArticle: true, isProper: true },
      { name: "Engineering", noArticle: true, isProper: true },
      { name: "Holodeck", noArticle: false, isProper: true },
      { name: "Sickbay", noArticle: true, isProper: true },
      { name: "Transporter Room", noArticle: false, isProper: true },
      { name: "Ready Room", noArticle: false, isProper: true },
      { name: "Science Lab", noArticle: false, isProper: true },
      { name: "Shuttlebay", noArticle: false, isProper: true },
      { name: "Observation Lounge", noArticle: false, isProper: true },
      { name: "Cargo Bay", noArticle: false, isProper: true },
    ],
    roomFeatures: {
      Bridge: ["Captain's chair", "tactical station", "viewscreen", "turbolift", "helm control"],
      "Ten Forward": ["bar", "large windows", "3D chess set", "replicator", "synthale dispenser"],
      Engineering: ["warp core", "isolinear racks", "master systems display", "jefferies tube", "dilithium chamber"],
      Holodeck: ["arch", "yellow grid", "control panel", "holographic emitter", "safeties manual"],
      Sickbay: ["biobed", "medical scanner", "surgical arch", "hypospray rack", "desktop monitor"],
      "Transporter Room": ["transporter pad", "control console", "pattern buffer", "targeting scanner", "sliding doors"],
      "Ready Room": ["fish tank", "desk", "sofa", "shakespeare volume", "earl grey replicator"],
      "Science Lab": ["microscopes", "sensor array", "stasis field", "specimen container", "laser cutter"],
      Shuttlebay: ["shuttlecraft", "launch pad", "atmospheric forcefield", "cargo crates", "flight control"],
      "Observation Lounge": ["model ships", "long table", "viewports", "gold ship relief", "presentation screen"],
      "Cargo Bay": ["shipping containers", "anti-grav sled", "blue barrel", "forcefield control", "airlock"],
    },
    items: [
      { name: "Type-2 Phaser", isProper: true },
      { name: "Bat'leth", isProper: true },
      { name: "Tricorder", isProper: true },
      { name: "Hypospray", isProper: true },
      { name: "Disruptor", isProper: true },
      { name: "PADD", isProper: true },
      { name: "Horga'hn", isProper: true },
      { name: "Ressikan Flute", isProper: true },
      { name: "Self-Sealing Stem Bolt", isProper: true },
      { name: "Isolinear Chip", isProper: true },
      { name: "Klingon Dagger", isProper: true },
    ],
  },
  {
    id: "classic",
    name: "Classic Mansion",
    suspects: [
      "Col. Mustard",
      "Miss Scarlet",
      "Prof. Plum",
      "Mr. Green",
      "Mrs. Peacock",
      "Mme. Rose",
      "Sgt. Gray",
      "Miss Peach",
      "Mrs. White",
      "Capt. Brown",
    ],
    rooms: [
      { name: "Kitchen", noArticle: false, isProper: false },
      { name: "Ballroom", noArticle: false, isProper: false },
      { name: "Conservatory", noArticle: false, isProper: false },
      { name: "Library", noArticle: false, isProper: false },
      { name: "Study", noArticle: false, isProper: false },
      { name: "Hall", noArticle: false, isProper: false },
      { name: "Lounge", noArticle: false, isProper: false },
      { name: "Dining Room", noArticle: false, isProper: false },
      { name: "Billiard Room", noArticle: false, isProper: false },
      { name: "Cellar", noArticle: false, isProper: false },
      { name: "Attic", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      Kitchen: ["iron stove", "walk-in pantry", "butcher block", "copper pans", "dumbwaiter"],
      Ballroom: ["grand piano", "crystal chandelier", "musicians' gallery", "polished floor", "french doors"],
      Conservatory: ["exotic plants", "glass roof", "wicker furniture", "stone fountain", "potting bench"],
      Library: ["tall bookshelves", "sliding ladder", "reading chair", "antique globe", "bust of Pallas"],
      Study: ["stone fireplace", "wall safe", "mahogany desk", "leather armchair", "oil portrait"],
      Hall: ["grand staircase", "coat rack", "telephone", "grandfather clock", "umbrella stand"],
      Lounge: ["velvet sofa", "gramophone", "drinks trolley", "heavy curtains", "card table"],
      "Dining Room": ["silverware", "banquet table", "oak sideboard", "candelabra", "crystal glasses"],
      "Billiard Room": ["pool table", "cue rack", "dartboard", "trophy cabinet", "smoking stand"],
      Cellar: ["wine barrels", "coal chute", "fuse box", "cobwebs", "workbench"],
      Attic: ["old trunks", "dusty mirrors", "dress form", "rocking horse", "exposed beams"],
    },
    items: [
      { name: "Candlestick", isProper: false },
      { name: "Dagger", isProper: false },
      { name: "Lead Pipe", isProper: false },
      { name: "Revolver", isProper: false },
      { name: "Rope", isProper: false },
      { name: "Wrench", isProper: false },
      { name: "Poison", isProper: false },
      { name: "Horseshoe", isProper: false },
      { name: "Trophy", isProper: false },
      { name: "Poker", isProper: false },
      { name: "Axe", isProper: false },
    ],
  },
  {
    id: "medieval",
    name: "Medieval Mystery",
    suspects: [
      "Sir Alistair",
      "Lady Eleanor",
      "The Friar",
      "The Minstrel",
      "The Blacksmith",
      "Princess Isabella",
      "The Jester",
      "The Alchemist",
      "The Squire",
      "The Abbess",
      "The Huntsman",
      "The Herbalist",
      "The Knight",
    ],
    rooms: [
      { name: "Throne Room", noArticle: false, isProper: false },
      { name: "Great Hall", noArticle: false, isProper: false },
      { name: "Dungeon", noArticle: false, isProper: false },
      { name: "Armory", noArticle: false, isProper: false },
      { name: "Chapel", noArticle: false, isProper: false },
      { name: "Stable", noArticle: false, isProper: false },
      { name: "Tower", noArticle: false, isProper: false },
      { name: "Courtyard", noArticle: false, isProper: false },
      { name: "Barracks", noArticle: false, isProper: false },
      { name: "Gatehouse", noArticle: false, isProper: false },
    ],
    roomFeatures: {
      "Throne Room": ["golden throne", "heraldic banners", "royal dais", "stone crest", "guard post"],
      "Great Hall": ["long table", "roaring hearth", "minstrel's gallery", "faded tapestry", "roasting spit"],
      Dungeon: ["rusty chains", "damp straw", "iron shackles", "water drip", "wooden stocks"],
      Armory: ["shield rack", "sharp swords", "whetstone", "armor stand", "training dummy"],
      Chapel: ["stone altar", "stained glass", "wooden pews", "holy relic", "confessional"],
      Stable: ["fresh hay", "horse stalls", "water trough", "saddle rack", "pitchfork"],
      Tower: ["spiral stairs", "arrow slit", "brass telescope", "warning bell", "trapdoor"],
      Courtyard: ["stone well", "target dummies", "wooden stocks", "central fountain", "cobblestones"],
      Barracks: ["wooden bunks", "armor stands", "dice table", "weapon rack", "footlocker"],
      Gatehouse: ["iron portcullis", "heavy winch", "murder holes", "drawbridge control", "boiling oil"],
    },
    items: [
      { name: "Broadsword", isProper: false },
      { name: "Chalice", isProper: false },
      { name: "Crossbow", isProper: false },
      { name: "Poison Ring", isProper: false },
      { name: "Mace", isProper: false },
      { name: "Scroll", isProper: false },
      { name: "Morning Star", isProper: false },
      { name: "Mandragora", isProper: true } /* Exotic/Proper name arguably */,
      { name: "Gauntlet", isProper: false },
      { name: "Dagger", isProper: false },
      { name: "Poisoned Wine", isProper: false },
    ],
  },
];

export const CONFIG = {
  // 85% for classic, the rest shared among others
  classicWeight: 0.85,
};
